#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_statusline_bfpath = true
    relativenumber = false
    sidebar_width = 50
    statusline_unicode_symbols = true
    bootstrap_before = "myspacevim#before"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "format"
